# Generated by Django 3.2.11 on 2022-01-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('user__first_name', 'user__last_name'), 'permissions': [('view_history', 'Can view history')]},
        ),
    ]
