"""
Django settings for storefront project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
import os

# the current project home directory
from celery.schedules import crontab

BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    # Django authentication system
    # identify users, allow them to log in, log out and change password and others.
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'debug_toolbar',
    'django_filters',
    # the name of the library is not the same as the name of the app
    'rest_framework',
    'djoser',
    'corsheaders',
    'silk',

    'playground',
    'store',
    'tags',
    'likes',

    'core',
]

# Middleware is a function that takes a request and either passes that request
# to the next middleware or return a response, each middleware can take the request
# and add something to it.
MIDDLEWARE = [
    # the order matters
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    # whitenoise middleware should be as high as possible
    # but should come after the security middleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # read the user information from the request and
    # set the user attributes on the request object
    # for example, the request.user will be either set to be an instance of
    # the anonymous user class or an actual user object.
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "debug_toolbar.middleware.DebugToolbarMiddleware",


]

# if DEBUG:
#     # the silk middleware not adding something to the incoming request,
#     # it processes the incoming request
#     MIDDLEWARE += ['silk.middleware.SilkyMiddleware', ]

ROOT_URLCONF = 'storefront.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]




CORS_ALLOWED_ORIGINS = [
    'http://localhost:8001',
    'http://127.0.0.1:8001',
]

# https://www.fomfus.com/articles/how-to-use-ip-ranges-for-django-s-internal_ips-setting/
# INTERNAL_IPS is a Django setting that works as a "security" filter,
# allowing Django to know whether it is OK (or not) to disclose sensitive
# information within its requests and Debug information output.
# It is also used by other modules, most notably Django Debug Toolbar to know
# if it is OK to show up.
INTERNAL_IPS = [
    # ...
    "10.0.2.2",
    # ...
]

WSGI_APPLICATION = 'storefront.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
# these are the files that are bundled with our applications

STATIC_URL = '/static/'
# Django knows where our static assets are located on disk
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# media refers to user uploaded files
# the endpoint to expose the media files
MEDIA_URL = '/media/'
# where the media files are stored in the file system
# the full path to a folder on disk that contains user uploaded files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

REST_FRAMEWORK = {
    # stop the DRF from converting decimal to string when serializing objects
    'COERCE_DECIMAL_TO_STRING': False,
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',
    # ]
    # the default permission class is AllowAny,
    # we set the default permission to IsAuthenticated, all API endpoints are
    # now closed for anonymous users.
    # we can supply a list of permission classes, if any fails, the client
    # would be able to access that views

}

# specific settings for rest framework simplejwt
SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('JWT',),
    # JWT should be the prefix for the authorization header
    'ACCESS_TOKEN_LIFETIME': timedelta(days=180),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=360),
}

AUTH_USER_MODEL = 'core.User'

DJOSER = {
    'SERIALIZERS': {
        'user_create': 'core.serializers.UserCreateSerializer',
        'current_user': 'core.serializers.UserSerializer',
    }
}


# the fake server doesn't have a user and password, leave it empty
# password saved here is unsafe, should use environment variable in production
DEFAULT_FROM_EMAIL = 'from@shopping.com'
# set site admins for send_admins,
# a list of tuples, each tuple (name, email)
ADMINS = [
    ('admin1', 'admin1@shopping.com'),
    ('admin2', 'admin2@shopping.com'),
]
# for smtp4dev,
# admin interface: host machine port 3000 -> docker port 80
# server: host machine port 2525 -> docker port 25


# for celery configurations

# setting the broker for the application and celery
# this setting means app -> redis -> celery
# intuitively only set redis -> celery, but actually also set app -> redis
# these are the settings inserted by celery
# to instruct the flow of messages from application to redis
# we can think message broker is part of celery system
# we just separate redis to running in docker, it should be a
# required running process for celery system.
# CELERY_BROKER_URL = 'redis://10.0.2.2:6379/1'

CELERY_BEAT_SCHEDULE = {
    'notify_customers': {
        'task': 'playground.tasks.notify_customers',
        # every Monday 7:30
        # 'schedule': crontab(day_of_week=1, hour=7, minute=30)
        # every 15 minutes
        # 'schedule': crontab(minute='*/15')
        'schedule': 5,
        'args': ['Hello world'],
        'kwargs': {},

    }
}

# # config redis as the caching backend
# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         # the location of the redis server
#         # database 1 has been used as message broker, use 2 as cache
#         "LOCATION": 'redis://10.0.2.2:6379/2',
#         # the data in cache will be time out in 10 mins
#         'TIMEOUT': 10 * 60,
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         }
#     }
# }


# configurations for logging <logger objects>
LOGGING = {
    'version': 1,
    # as a best practice, we should always set this to be False,
    # There are other loggers that come with Django or other libraries we use,
    # we don't want to disable them,
    # we want to capture everything that comes with tem.
    'disable_existing_loggers': False,
    # what to do with log messages, write to the console or write to a file
    # <handlers only define handlers, logger will actually set them>
    # < all things here are for configuring logger objects>
    'handlers': {
        # writing messages to the console
        'console': {
            'class': 'logging.StreamHandler'
        },
        # writing messages to file
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'general.log',
            'formatter': 'verbose',
        }
    },

    # configurate the logger objects we create in the logic codes
    'loggers': {
        # capture any log messages from this app
        # <configure the loggers from playground app>
        # 'playground': {}
        # capture only messages from a module
        # <configure the loggers from playground views module>
        # 'playground.view': {}
        # capture all messages from all apps

        # <configure the loggers for all apps>
        '': {
            # after capturing the messages, write them both to console and files
            'handlers': ['console', 'file'],
            # When we define a logger, we need to specify a level,
            # this logger will only capture log messages at this level or higher.
            # the level of log messages: DEBUG, INFO, WARNING, ERROR, CRITICAL.
            # 'level': 'ERROR',
            # get the log level from environment variables,
            # and supply a default value
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
        },

    },

    # define how log messages should be formatted
    'formatters': {
        # 'simple': {},
        'verbose': {
            # the format of our log messages,
            # these log messages have different attributes
            # https://docs.python.org/3/library/logging.html#
            'format': '{asctime} ({levelname}) - {name} - {message}',
            # setting style to '{' will translate {} to string.format()
            # the strings listed above will be passed to string.format()
            # $: will use string.Template class
            'style': '{'
        },
    }
}
# 2022-01-25 23:36:23,339 (INFO) - django.utils.autoreload - Watching for file changes with StatReloader
# django comes with a few built-in loggers
